// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered suggestions for improving a CV, focusing on spelling errors and outdated language.
 *
 * - `cvCheckerSuggestions`: A function that takes CV content as input and returns improvement suggestions.
 * - `CvCheckerInput`: The input type for the `cvCheckerSuggestions` function.
 * - `CvCheckerOutput`: The return type for the `cvCheckerSuggestions` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CvCheckerInputSchema = z.object({
  cvDataUri: z
    .string()
    .describe(
      "A CV file as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type CvCheckerInput = z.infer<typeof CvCheckerInputSchema>;

const CvCheckerOutputSchema = z.object({
  suggestions: z
    .string()
    .describe(
      'AI-powered suggestions for improving the CV, focusing on spelling errors and outdated language. Suggestions should be actionable.'
    ),
});
export type CvCheckerOutput = z.infer<typeof CvCheckerOutputSchema>;

export async function cvCheckerSuggestions(input: CvCheckerInput): Promise<CvCheckerOutput> {
  return cvCheckerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'cvCheckerPrompt',
  input: {schema: CvCheckerInputSchema},
  output: {schema: CvCheckerOutputSchema},
  prompt: `You are an AI assistant designed to provide suggestions for improving a CV.

  Analyze the content of the CV provided in the media and provide actionable suggestions to:
  - Correct spelling errors
  - Update outdated language

  CV: {{media url=cvDataUri}}

  Suggestions:`,
});

const cvCheckerFlow = ai.defineFlow(
  {
    name: 'cvCheckerFlow',
    inputSchema: CvCheckerInputSchema,
    outputSchema: CvCheckerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
